## Functions for reading SAXS profiles in .dat format
## specifically, as generated by BIOXTAS RAW

library(tidyverse)
library(rjson) # for reading .dat headers
library(lubridate) # for parsing datetime from same

# this only reads the profile data from each file
read_saxsdats = function(datfiles){
  datfiles %>% 
    read_delim(
      delim = "  ",
      comment = '#',
      col_names = c("q", "iq", "err"),
      col_types = list(col_double(), col_double(), col_double()),
      id = "fname"
    ) %>% 
    # parse filename
    group_by(fname) %>% 
    mutate(fname = basename(fname)) %>% 
    separate(
      fname,
      into = c(
        "samp",
        "temp",
        "press",
        "pdir",
        "rep"
      ),
      remove = FALSE
    ) %>% 
    # get rid of units
    mutate(across(
      all_of(c("temp", "press")),
      function(st){st %>% str_extract("(\\d)+") %>% as.numeric()}
    ))
}

# this only reads the header data from each file
read_saxsmeta = function(datfiles){
  datfiles %>% 
    lapply(
      .,
      function(file){
        file %>% 
          read_file() %>% 
          # strip everything up to and including the HEADER line
          sub(".*### HEADER:", '', .) %>% 
          # strip comment chars
          gsub('#', '', .) %>% 
          # parse the JSON
          rjson::fromJSON() %>% 
          .$counters %>% as.list() %>% 
          as_tibble() %>% 
          mutate(
            date = date %>% parse_date_time(order = "%a%b%d%H%M%S%Y"),
            fname = file %>% basename(),
          )
      }
    ) %>% 
    bind_rows()
}

# this does both and joins the results by filename
read_saxsall = function(datfiles){
  datfiles %>% 
    read_saxsmeta() %>% 
    group_by(across(everything())) %>% 
    right_join(
      datfiles %>% 
        read_saxsdats(),
      by = "fname"
    )
}